### ISSUE TITLE
Overall architecture discussion

### ISSUE THREAD

**Issue by MBARIMike** [biofloat/biofloat#5]
This project originated with need to make better use of the oxygen data from Argo drifting floats. In 2015 MBARI summer intern @josejramirez helped us get started with using Python and Jupyter Notebooks for doing the computations and visualizations.

The project is now "grown up" and is getting some software engineering to make it usable for others. It has been moved to this GitHub repo and now Travis CI and Coveralls integration to give confidence that the code works. The plan is to eventually post the module on PyPI do that people can easily install it with `pip install biofloat`.

During Jose's internship we discovered that crawling various Internet sites to retrieve data and metadata takes quite a bit of time. Therefore, I'd like to add a simple database capability so that this information can be locally cached. I intend to experiment with various solutions and see how they work.

Are there any requirements I need to consider as I do this experimentation?

**Comment by MBARIMike** [comment]
I consider 3 options for caching Argo information: Mongodb, Sqlite3, and HDF. Here are some pros and cons:

##### Mongodb
* Pros: It's what all the cool kids are using, simple key, value document store
* Cons: Requires a server installation, potential limitations of key, value store

##### Sqlite3
* Pros: Included with Python, powerful generic SQL capabilities
* Cons: Requires upfront schema design and is brittle in the face of evolving requirements

##### HDF
* Pros: Integrated support with PyTables for storing Pandas DataFrames
* Cons: Requires installation of HDF and all it's prerequisites

Given these considerations I'll try and implementation using HDF. It promises to be as simple as:

    store = HDFStore('store.h5')
    store['df'] = df  # save it
    store['df']  # load it

**Comment by MBARIMike** [comment]
The HDF solution is very simple on the surface. An interesting problem arose in storing empty Pandas DataFrames to mark a float/profile as having no valid data &mdash; it took a ridiculous amount of disk space. See the [stackoverflow question](http://stackoverflow.com/questions/33658783/empty-pandas-dataframes-saved-with-hdfstore-make-very-large-hdf-files) detailing the problem. The problem has been temporarily alleviated by storing a DataFrame containing a single NaN.

See the [biofloat notebooks](https://github.com/biofloat/biofloat/tree/master/notebooks) for testing of the cache file operation. The overall architecture discussion now becomes: are oceanographers comfortable working with the Pandas DataFrame directly to perform analysis and visualization of Bio-Argo data? What additional functions should the biofloat package provide to make it easier to work with Bio-Argo data?

**Comment by biofloat** [comment]
See the tweets following sharing this experience with @HDFGroup: https://twitter.com/TedHabermann/status/678339797929230336
